version: '3.8'

services:

# zenohd
  zenoh:
    image: docker.io/eclipse/zenoh:latest
    container_name: zenoh
    ports:
      - "7447:7447"
      - "8000:8000"
    networks:
      - zenoh-network
    restart: unless-stopped
    environment:
      - ZENOH_HOME=/zenoh
      - ZENOH_STORAGE=/zenoh/storage
    volumes:
      - zenoh-data:/zenoh/storage

# Flask Server (SSE)
  flask-app:
    container_name: flask-server
    build:
      context: ./flask_server
      dockerfile: Containerfile
    network_mode: host
    restart: unless-stopped
    environment:
      - ZENOH_SUBSCRIBE_KEY=demo/example/zenoh_sub
      - ZENOH_PUBLISH_KEY=demo/example/zenoh_pub

# SQL (Postgres)
  postgres:
    image: docker.io/postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: estufa
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

# # IHM
#   ihm:
#     container_name: ihm
#     build:
#       context: "/home/nicolas/Estufa"
#       dockerfile: Containerfile
#     network_mode: host
#     restart: unless-stopped

networks:
  zenoh-network:
    driver: bridge

volumes:
  zenoh-data:
    driver: local
  postgres-data:
    driver: local