FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN apt-get update && apt-get install -y libssl-dev libcurl4-openssl-dev

RUN pip install --no-cache-dir flask flask-cors eclipse-zenoh

EXPOSE 5000

CMD ["python", "send_to_client.py"]