# Base image
FROM python:3.11-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia todos os arquivos para o diretório de trabalho
COPY . /app

# Instala dependências de sistema necessárias para Zenoh e PostgreSQL
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libcurl4-openssl-dev \
    libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Instala as dependências Python do projeto
RUN pip install --no-cache-dir flask flask-cors psycopg2-binary eclipse-zenoh

# Expõe a porta 7766 para acesso ao serviço Flask
EXPOSE 7766

# Comando para iniciar o servidor Flask
CMD ["python", "database_connection.py"]
